'use strict';

// Builds a release-note DRAFT from a git range — classified, linked to
// features/bugs/decisions, written under docs/product/generated/ (a
// disposable, rebuildable location, same tier as change-reports/). Never
// creates a GitHub release, never writes docs/release-notes-*.md directly —
// that remains a separate, explicitly authorized action per the brief.

const fs = require('fs');
const path = require('path');
const { GENERATED_ROOT } = require('../lib/repoRoot');
const build = require('../lib/build');
const { buildChangeReport } = require('../lib/changeReport');
const { stableStringify } = require('../lib/stableJson');
const { atomicWriteFileSync } = require('./atomicWrite');

// Conventional-commit-ish prefix classification, matching this repository's
// actual commit style (see `git log --oneline`: "fix(ci): ...",
// "docs(product): ...", "feat: ..."). A commit that doesn't match any
// known prefix is classified "Changed" rather than guessed into a more
// specific bucket.
const PREFIX_CATEGORY = [
  [/^feat(\(|:)/i, 'Added'],
  [/^fix(\(|:)/i, 'Fixed'],
  [/^perf(\(|:)/i, 'Performance'],
  [/^refactor(\(|:)/i, 'Changed'],
  [/^docs(\(|:)/i, 'Documentation'],
  [/^test(\(|:)/i, 'Changed'],
  [/^chore(\(|:)/i, 'Changed'],
  [/^ci(\(|:)/i, 'Changed'],
  [/^security(\(|:)/i, 'Security'],
  [/^deprecate(\(|:)/i, 'Deprecated'],
  [/^remove(\(|:)/i, 'Removed'],
];

function classifyCommitSubject(subject) {
  for (const [re, category] of PREFIX_CATEGORY) {
    if (re.test(subject)) return category;
  }
  return 'Changed';
}

function buildReleaseDraft(fromRef, toRef) {
  const { parsed, built } = build.assemble();
  const report = buildChangeReport(fromRef, toRef, parsed, built.subsystems, built.sourceIndex);

  const byCategory = {};
  for (const c of report.commits) {
    const category = classifyCommitSubject(c.subject);
    (byCategory[category] = byCategory[category] || []).push(c);
  }

  const draft = {
    from_ref: fromRef,
    to_ref: toRef,
    from_commit: report.from_commit,
    to_commit: report.to_commit,
    generated_at: new Date().toISOString(),
    categories: byCategory,
    affected_features: report.affected_features,
    bugs_referenced: report.bugs_changed,
    decisions_referenced: report.decisions_changed,
    known_issues_note: 'Not automatically populated — review open BUG-### records with Status "Open" or "Investigating" before publishing.',
    publish_note: 'DRAFT ONLY. Does not create a GitHub release or docs/release-notes-*.md. Publishing remains a separately authorized human action.',
  };
  return draft;
}

function renderReleaseDraftMd(draft) {
  const lines = [];
  lines.push(`# Release Draft — ${draft.from_ref} → ${draft.to_ref}`);
  lines.push('');
  lines.push('**DRAFT ONLY — not a published release.** Generated by `automation release-draft`; review before turning into `docs/release-notes-*.md`.');
  lines.push('');
  const order = ['Added', 'Changed', 'Fixed', 'Performance', 'Reliability', 'Security', 'UI/UX', 'Documentation', 'Deprecated', 'Removed'];
  for (const category of order) {
    const commits = draft.categories[category];
    if (!commits || commits.length === 0) continue;
    lines.push(`## ${category}`);
    for (const c of commits) lines.push(`- ${c.subject} (\`${c.short}\`)`);
    lines.push('');
  }
  lines.push('## Known Issues');
  lines.push(draft.known_issues_note);
  lines.push('');
  lines.push('## Affected Features');
  lines.push(draft.affected_features.length ? draft.affected_features.join(', ') : 'None detected.');
  lines.push('');
  lines.push(draft.publish_note);
  return lines.join('\n') + '\n';
}

function writeReleaseDraft(fromRef, toRef) {
  const draft = buildReleaseDraft(fromRef, toRef);
  const safe = (s) => s.replace(/[^a-zA-Z0-9._-]/g, '_');
  const baseName = `${safe(fromRef)}_TO_${safe(toRef)}`;
  const dir = path.join(GENERATED_ROOT, 'release-drafts');
  fs.mkdirSync(dir, { recursive: true });
  const mdPath = path.join(dir, `${baseName}.md`);
  const jsonPath = path.join(dir, `${baseName}.json`);
  // Routed through the shared atomic-write choke point (temp-then-rename)
  // like every other write path in automation/ — a crash mid-write must
  // never leave a torn file under generated/release-drafts/, which (per
  // Part 4's README) is committed to git, unlike exports/.
  atomicWriteFileSync(mdPath, renderReleaseDraftMd(draft));
  atomicWriteFileSync(jsonPath, stableStringify(draft));
  return { mdPath, jsonPath, draft };
}

module.exports = { buildReleaseDraft, renderReleaseDraftMd, writeReleaseDraft, classifyCommitSubject };
