'use strict';

// Stage 1 Knowledge Engine — compiles docs/product/generated/knowledge-index.json,
// a portal-oriented projection of the canonical feature registry. This is a
// GENERATED artifact like every other file under docs/product/generated/ —
// never hand-edited, never authoritative, regenerated by `build` from the
// same canonical Markdown as feature-index.json. It does not parse Markdown
// itself; it derives entirely from already-parsed structures
// (lib/featureIndex.js's records, lib/roadmapDashboard.js's dashboard,
// parsed.bugs) so there is exactly one Markdown-parsing implementation in
// this tool, per scripts/product-docs/README.md's "do not duplicate
// canonical parsing logic" convention.
//
// Field list is deliberately the minimum needed to answer an operator
// question without inventing anything (see
// docs/product/features/AI-FEAT-058_*.md § Knowledge Record Schema for the
// full rationale of each field, and for the fields considered and rejected
// as unnecessary for Stage 1 — entry-point/navigation and screenshot
// fields, since no canonical source for either exists yet).

const { resolveFeatureOperatorStatus } = require('./statusResolution');

function dedupSorted(items) {
  return Array.from(new Set((items || []).filter(Boolean))).sort();
}

function buildKnowledgeIndex(parsed, { featureIndex, dashboard }) {
  const milestoneById = new Map((dashboard.milestones || []).map((m) => [m.id, m]));

  return featureIndex.map((f) => {
    const featureFile = parsed.features.get(f.feature_id);

    const openBugs = (f.related_bugs || []).map((bugId) => {
      const bug = parsed.bugs.get(bugId);
      return { id: bugId, status: bug ? (bug.header['Status'] || 'Evidence pending') : 'Evidence pending' };
    });
    // Prefix match, not exact — a bug status can be e.g. "Fixed (recurring
    // pattern — see Prevention)", still a resolved bug (found via real data
    // during Stage 1 verification: BUG-006 on this very feature).
    const openBugCount = openBugs.filter((b) => !/^(Fixed|Resolved|Closed)\b/i.test(b.status)).length;

    const { operatorStatus, reason, evidence } = resolveFeatureOperatorStatus(f, { openBugCount });

    const relatedFeatures = dedupSorted([
      ...(f.related_features || []),
      ...(f.dependencies || []),
      ...(f.dependents || []),
      ...(f.parent_feature || []),
      ...(f.subfeatures || []),
    ]);

    const roadmapRelationship = (f.roadmap_ids || []).map((rmId) => {
      const m = milestoneById.get(rmId);
      return { roadmapId: rmId, status: m ? m.status : 'Evidence pending' };
    });

    const sourceFiles = dedupSorted([
      f.canonical_document,
      ...(f.related_code_paths || []),
      ...(f.related_technical_docs || []),
    ]);

    const futureEnhancementsText = (featureFile && featureFile.futureEnhancements || '').trim();
    const futureEnhancements = futureEnhancementsText && !/^none recorded\.?$/i.test(futureEnhancementsText)
      ? futureEnhancementsText
      : null;

    return {
      id: f.feature_id,
      title: f.name,
      summary: f.summary,
      status: f.status,
      operatorStatus,
      searchTerms: dedupSorted([...(f.aliases || []), ...(f.search_keywords || [])]),
      category: f.category,
      whatItDoes: f.summary,
      availability: { operatorStatus, reason, evidence },
      relatedFeatures,
      roadmapRelationship,
      knownLimitations: {
        openBugs,
        evidenceGapCount: (f.documentation_completeness && f.documentation_completeness.evidence_gap_count) || 0,
        futureEnhancements,
      },
      // Kept distinct from sourceFiles below: `sourceFiles` is an
      // alphabetically-sorted merge of the canonical document, related code
      // paths, and related technical docs (for completeness/browsability),
      // which means sourceFiles[0] is NOT reliably the canonical document —
      // found during the PR #5 forensic review, where 39/58 records cited
      // something other than their own feature file as the "primary"
      // source, including 5 records citing a bare, pathless fragment (e.g.
      // "#12", a pre-existing parsing artifact of a multi-footnote
      // citation in lib/subsystems.js's parseRelatedTechnicalDocs — see
      // that review's Phase 3 finding). knowledgeEngine.js's
      // sourcesForRecord() must cite this field, never sourceFiles[0].
      canonicalDocument: f.canonical_document,
      sourceFiles,
      sourceAuthority: 'canonical', // docs/product/features/ tier — see scripts/product-docs/README.md Authority model
      lastUpdated: {
        introducedVersion: f.introduced_version,
        lastModifiedVersion: f.last_modified_version,
        evidenceStatus: f.evidence_status,
      },
    };
  });
}

module.exports = { buildKnowledgeIndex };
