'use strict';

// Part 7C — generated ownership manifest. A re-projection of ALREADY
// explicit evidence Part 4 already parses (feature Related Files, subsystem
// source directories, feature Testing coverage citations) into the six
// lookup directions the brief asks for. This is deliberately NOT where
// multi-signal scored resolution lives — see automation/ownershipEngine.js
// for that (require-graph, git co-change history, decision/bug citation,
// weighted confidence). This manifest only ever restates what a feature file
// already explicitly says; a path absent here is unresolved, never guessed —
// same "generated is a locator, never a new source of facts" rule as every
// other file under docs/product/generated/.

const { compareIds } = require('./ids');

function buildOwnershipManifest(parsed, built) {
  const { featureIndex, subsystems, sourceIndex } = built;

  const featureToCodePaths = {};
  const featureToTests = {};
  for (const f of featureIndex) {
    featureToCodePaths[f.feature_id] = f.related_code_paths.slice().sort();
    featureToTests[f.feature_id] = f.related_tests.slice().sort();
  }

  const codePathToFeatures = {};
  for (const [file, subIds] of sourceIndex.byFile) {
    const features = new Set();
    for (const subId of subIds) {
      const s = subsystems.find((x) => x.id === subId);
      if (s) for (const feat of s.primaryFeatures) features.add(feat);
    }
    codePathToFeatures[file] = { features: Array.from(features).sort(compareIds), confidence: 'explicit' };
  }

  const testToFeatures = {};
  for (const [featId, tests] of Object.entries(featureToTests)) {
    for (const t of tests) {
      if (!testToFeatures[t]) testToFeatures[t] = [];
      if (!testToFeatures[t].includes(featId)) testToFeatures[t].push(featId);
    }
  }
  for (const t of Object.keys(testToFeatures)) testToFeatures[t].sort(compareIds);

  const subsystemToFeatures = {};
  const ipcToFeatures = {};
  const serviceToFeatures = {};
  for (const s of subsystems) {
    subsystemToFeatures[s.id] = s.primaryFeatures.slice();
    // Best-effort derivation, not a new signal: a subsystem whose OWN
    // explicitly-sourced directories include main/ or services/ is labeled
    // as touching the IPC or service layer respectively. Never claims a
    // specific IPC channel or service call — that finer grain is
    // automation/ownershipEngine.js's job, not this manifest's.
    const touchesMain = s.sourceDirectories.some((d) => d === 'main' || d.startsWith('main/'));
    const touchesServices = s.sourceDirectories.some((d) => d === 'services' || d.startsWith('services/'));
    if (touchesMain) ipcToFeatures[s.id] = { features: s.primaryFeatures.slice(), basis: 'derived — subsystem source directories include main/' };
    if (touchesServices) serviceToFeatures[s.id] = { features: s.primaryFeatures.slice(), basis: 'derived — subsystem source directories include services/' };
  }

  return {
    feature_to_code_paths: featureToCodePaths,
    code_path_to_features: codePathToFeatures,
    feature_to_tests: featureToTests,
    test_to_features: testToFeatures,
    subsystem_to_features: subsystemToFeatures,
    ipc_to_features: ipcToFeatures,
    service_to_features: serviceToFeatures,
    note: 'code_path_to_features only lists paths already explicitly authored in some feature\'s Related Files section — a path not appearing here is unresolved, not unowned. Use "node scripts/product-docs/cli.js automation ownership <path>" for a multi-signal, confidence-scored resolution of an arbitrary path.',
  };
}

function renderOwnershipManifestMd(manifest) {
  const lines = [];
  lines.push('# Ownership Manifest');
  lines.push('');
  lines.push('Generated by `node scripts/product-docs/cli.js build`. Never hand-edit — see `lib/ownershipManifest.js`.');
  lines.push('');
  lines.push(manifest.note);
  lines.push('');
  lines.push('## Subsystem → Features');
  lines.push('');
  for (const [subId, feats] of Object.entries(manifest.subsystem_to_features).sort()) {
    lines.push(`- **${subId}**: ${feats.length ? feats.join(', ') : 'none'}`);
  }
  lines.push('');
  lines.push('## IPC-layer subsystems (derived — main/)');
  lines.push('');
  const ipcEntries = Object.entries(manifest.ipc_to_features);
  lines.push(ipcEntries.length ? ipcEntries.map(([id, v]) => `- **${id}**: ${v.features.join(', ')}`).join('\n') : 'None detected.');
  lines.push('');
  lines.push('## Service-layer subsystems (derived — services/)');
  lines.push('');
  const svcEntries = Object.entries(manifest.service_to_features);
  lines.push(svcEntries.length ? svcEntries.map(([id, v]) => `- **${id}**: ${v.features.join(', ')}`).join('\n') : 'None detected.');
  lines.push('');
  lines.push(`## Coverage`);
  lines.push('');
  lines.push(`- ${Object.keys(manifest.code_path_to_features).length} explicitly-owned code path(s).`);
  lines.push(`- ${Object.keys(manifest.test_to_features).length} test file(s) with a discoverable feature owner via Testing coverage citations.`);
  return lines.join('\n') + '\n';
}

module.exports = { buildOwnershipManifest, renderOwnershipManifestMd };
