name: Build and Release AutoIngest

on:
  push:
    tags:
      - 'v*'

jobs:

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create service account key
        shell: bash
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$SERVICE_ACCOUNT_KEY" > config/service-account-key.json

      - name: Build and publish Mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist:mac -- -p always

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create service account key
        shell: bash
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$SERVICE_ACCOUNT_KEY" > config/service-account-key.json

      - name: Build and publish Windows
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist:win -- -p always
